-- MySQL Script generated by MySQL Workbench
-- sáb 25 fev 2023 09:59:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `sobrenome_usuario` VARCHAR(45) NOT NULL,
  `email_usuario` VARCHAR(80) NOT NULL,
  `nivel_usuario` TINYINT(10) NOT NULL,
  `status_usuario` VARCHAR(10) NOT NULL,
  `senha_usuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_usuario_UNIQUE` (`email_usuario` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`acomodacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acomodacao` (
  `id_acomodacao` INT NOT NULL AUTO_INCREMENT,
  `tipo_acomodacao` VARCHAR(80) NOT NULL,
  `descricao_acomodacao` LONGTEXT NOT NULL,
  `status_acomodacao` VARCHAR(10) NOT NULL,
  `imagem_acomodacao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_acomodacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cupom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cupom` (
  `id_cupom` INT NOT NULL AUTO_INCREMENT,
  `codigo_cupom` VARCHAR(10) NOT NULL,
  `data_cupom` DATETIME NOT NULL,
  `validade_cupom` DATETIME NOT NULL,
  `desconto_cupom` INT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cupom`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao` (
  `id_avaliacao` INT NOT NULL AUTO_INCREMENT,
  `data_avaliacao` DATETIME NOT NULL,
  `pontuacao_avaliacao` TINYINT(5) NOT NULL,
  `descricao_avaliacao` LONGTEXT NOT NULL,
  `status_avaliacao` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_avaliacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `checkin_reserva` DATE NOT NULL,
  `checkout_reserva` DATE NOT NULL,
  `qtd_pessoas_reserva` INT(10) NOT NULL,
  `total_reserva` DECIMAL(10,2) NOT NULL,
  `total_desconto_reserva` DECIMAL(10,2) NULL,
  `data_reserva` DATE NOT NULL,
  `confirmacao_reserva` TINYINT NOT NULL,
  `data_confirmacao_reserva` DATE NOT NULL,
  `acomodacao_id_acomodacao` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `cupom_id_cupom` INT NOT NULL,
  `avaliacao_id_avaliacao` INT NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reserva_acomodacao_idx` (`acomodacao_id_acomodacao` ASC) VISIBLE,
  INDEX `fk_reserva_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_reserva_cupom1_idx` (`cupom_id_cupom` ASC) VISIBLE,
  INDEX `fk_reserva_avaliacao1_idx` (`avaliacao_id_avaliacao` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_acomodacao`
    FOREIGN KEY (`acomodacao_id_acomodacao`)
    REFERENCES `mydb`.`acomodacao` (`id_acomodacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_cupom1`
    FOREIGN KEY (`cupom_id_cupom`)
    REFERENCES `mydb`.`cupom` (`id_cupom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_avaliacao1`
    FOREIGN KEY (`avaliacao_id_avaliacao`)
    REFERENCES `mydb`.`avaliacao` (`id_avaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`adicionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adicionais` (
  `id_adicionais` INT NOT NULL AUTO_INCREMENT,
  `item_adicionais` VARCHAR(45) NOT NULL,
  `descricao_adicionais` LONGTEXT NOT NULL,
  `valor_adicionais` DECIMAL(10,2) UNSIGNED NOT NULL,
  `imagem_adicionais` VARCHAR(255) NOT NULL,
  `reserva_id_reserva` INT NOT NULL,
  PRIMARY KEY (`id_adicionais`),
  INDEX `fk_adicionais_reserva1_idx` (`reserva_id_reserva` ASC) VISIBLE,
  CONSTRAINT `fk_adicionais_reserva1`
    FOREIGN KEY (`reserva_id_reserva`)
    REFERENCES `mydb`.`reserva` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consumo` (
  `id_consumo` INT NOT NULL AUTO_INCREMENT,
  `item_consumo` VARCHAR(45) NOT NULL,
  `local_consumo` VARCHAR(10) NOT NULL,
  `qtd_item_consumo` INT UNSIGNED NOT NULL,
  `data_consumo` DATETIME NOT NULL,
  `reserva_id_reserva` INT NOT NULL,
  PRIMARY KEY (`id_consumo`),
  INDEX `fk_consumo_reserva1_idx` (`reserva_id_reserva` ASC) VISIBLE,
  CONSTRAINT `fk_consumo_reserva1`
    FOREIGN KEY (`reserva_id_reserva`)
    REFERENCES `mydb`.`reserva` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
